### ISSUE TITLE
Bug in geometry rotation

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ReefGuideAPI.jl#37]
When assessing potential sites an initial geometry is provided to `assess_reef_site()` and it is rotated around its centroid.

https://github.com/open-AIMS/ReefGuideAPI.jl/blob/871ccc86c80f9cd8ae70c4fecc2d8f855c829f31/src/site_assessment/best_fit_polygons.jl#L58

I think there is a bug here. `rotations` (the degree positions to rotate) is given as the absolute rotational value in degrees.

```julia
rot_start = (start_rot - (degree_step * n_per_side))
rot_end = (start_rot + (degree_step * n_per_side))
rotations = rot_start:degree_step:rot_end

# ... later in the loop
for (j, r) in enumerate(rotations)
    rot_geom = rotate_geom(geom, r, target_crs)
    # ...
end
```

In the implementation above, `r` would be the degree at which the geometry should be rotated to *not* the degree to rotate by.

For clarity, where `start_rot` is set to -109.19, then in the first loop `r = -109.19`:

`rotate_geom(geom, -109.19, target_crs)`

The docstring for `rotate_geom()` states:

> Rotate target `geom` by `degrees` rotation in clockwise direction. `target_crs` is applied
to output geometry.

In the above example, the geom would be rotated -109.19 degrees!

Potential solution:

Change `rotate_geom()` to rotate the geometry to a **target rotation**, instead of the number of degrees to rotate by.

**Comment by ConnectedSystems** [comment]
The above may explain some strange behaviour where polygons are not well aligned as one might expect:

![image](https://github.com/user-attachments/assets/467c722c-e8b7-4297-961a-e867c2e19942)


Or where potential deployment locations are entirely missed (the initial search rotation is off):

![image](https://github.com/user-attachments/assets/055b6169-2f21-480f-9639-f39cf1f8bf08)

**Comment by BG-AIMS** [comment]
> In the implementation above, `r` would be the degree at which the geometry should be rotated to _not_ the degree to rotate by.
> 
> For clarity, where `start_rot` is set to -109.19, then in the first loop `r = -109.19`:
> 
> `rotate_geom(geom, -109.19, target_crs)`
> 
> The docstring for `rotate_geom()` states:
> 
> > Rotate target `geom` by `degrees` rotation in clockwise direction. `target_crs` is applied
> > to output geometry.
> 
> In the above example, the geom would be rotated -109.19 degrees!

Sorry I don't think I understand how `degree at which geometry should be rotated` and `degree to rotate by` differ? 
I think the rotation by -109.19degrees is intended since it is relative to the reef edge angle that has been identified. So if the reef edge angle was identified as -109 degrees and the polygon is horizontal at 0 degrees then rotating it by -109 degrees would align it with the correct reef edge angle.
E.g. here the yellow polygons are rotated by the angle of the hexagon edge, whereas the blue boxes are at 0 degrees (unrotated).
![image](https://github.com/user-attachments/assets/8309badf-eeac-4ea2-80a2-c0de8b6a6bef)

On the missing data/incorrect angles that seem to be happening I suspect:
- I think that the reef-edge angle may not necessarily be the best angle to align with suitability which is why we are seeing sites being filtered out or not as aligned as you'd expect. We could get around this by increasing the number of rotations that are performed on each side, but then we will probably end up not matching the reef-edge. 
- The 'reef-edge' angle would also be influenced by the GBRMPA reef outline polygons which could also be influencing how different the angles look on the satellite imagery.

**Comment by ConnectedSystems** [comment]
> We could get around this by increasing the number of rotations that are performed on each side, but then we will probably end up not matching the reef-edge.

It will increase computation time too. But generally it seems viable locations follow the reef edge, it's just certain cases where they don't and they may be filtered out by ignoring locations where the majority of the polygon won't fit anyway...
